#!/bin/bash

# Verifica que se pasen exactamente 5 argumentos
if [ $# -ne 5 ]; then
    echo "Uso: $0 FILAS COLUMNAS DELAY TURNOS SEED"
    exit 1
fi

# Ejecuta el master con los argumentos recibidos
./bin/master "$1" "$2" "$3" "$4" "$5" ./bin/view ./bin/player